version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /SLASHED-for-WP/integrations/bricks/editor-app
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /SLASHED-for-WP/admin-app
    schedule:
      interval: weekly
