/**
 * Override CSS generation + import.
 *
 * Mirrors the framework's own override contract: customised tokens are emitted
 * inside `@layer slashed.overrides { :root { … } }` (see docs/architecture.md —
 * `slashed.overrides` is the reserved consumer escape hatch and sits last in
 * the cascade, so these win without `!important`). A bare `:root { … }` mode is
 * also offered for consumers who don't use cascade layers.
 */
import { frameworkVersion } from './model.js';

/**
 * Sanitize a single declaration value so it cannot break out of its CSS
 * declaration. A legitimate custom-property value never needs a top-level
 * `;`, `{`, or `}`, nor comment delimiters — stripping them prevents a pasted
 * or fat-fingered value like `0; } body { display:none } /*` from corrupting
 * the generated `:root {}` block or the live preview, and keeps generate/parse
 * a faithful round-trip.
 *
 * @param {string} value raw value
 * @returns {string} value safe to interpolate into a declaration
 */
export function sanitizeValue(value) {
  if (value == null) return '';
  return String(value)
    .replace(/\/\*[\s\S]*?\*\//g, ' ') // drop comment blocks
    .replace(/[;{}]/g, ' ') // strip structural characters
    .replace(/[/*]{2,}/g, ' ') // neutralise stray comment delimiters
    .replace(/\s+/g, ' ')
    .trim();
}

/**
 * Build the override CSS string from an override map.
 *
 * @param {Record<string,string>} overrides token name -> value
 * @param {object} [opts]
 * @param {'layer'|'root'} [opts.mode='layer'] output framing
 * @param {boolean} [opts.banner=true] include a generated-by header comment
 * @returns {string} CSS text ('' when there are no overrides)
 */
export function generateCSS(overrides, opts = {}) {
  const { mode = 'layer', banner = true } = opts;
  const names = Object.keys(overrides).sort((a, b) => a.localeCompare(b));
  if (names.length === 0) return '';

  const decls = names.map((n) => `${n}: ${sanitizeValue(overrides[n])};`);

  const indent = mode === 'layer' ? '\t\t' : '\t';
  const body = decls.map((d) => `${indent}${d}`).join('\n');

  let out = '';
  if (banner) {
    const v = frameworkVersion ? ` v${frameworkVersion}` : '';
    out +=
      `/* SLASHED override tokens${v} — generated by the SLASHED configurator.\n` +
      `   Load this AFTER the SLASHED stylesheet. ${names.length} token${
        names.length === 1 ? '' : 's'
      } customised. */\n`;
  }

  if (mode === 'layer') {
    out += `@layer slashed.overrides {\n\t:root {\n${body}\n\t}\n}\n`;
  } else {
    out += `:root {\n${body}\n}\n`;
  }
  return out;
}

/**
 * Parse `--sf-*` custom-property declarations out of arbitrary CSS text.
 *
 * Tolerant of wrappers (@layer, :root, comments, whitespace): it scans for
 * `--sf-name:` and reads the value up to the matching top-level `;`, honouring
 * nested parentheses so `clamp()`, `oklch(from …)`, and `light-dark()` values
 * survive intact.
 *
 * @param {string} text pasted CSS
 * @returns {Record<string,string>} token name -> value
 */
export function parseCSS(text) {
  const result = {};
  if (!text) return result;

  // Strip block comments so a commented-out token isn't imported.
  const css = text.replace(/\/\*[\s\S]*?\*\//g, '');

  const re = /(--sf-[\w-]+)\s*:/g;
  let m;
  while ((m = re.exec(css)) !== null) {
    const name = m[1];
    let i = m.index + m[0].length;
    let depth = 0;
    let quote = ''; // current open quote char ('"' or "'"), or '' when outside
    let value = '';
    for (; i < css.length; i++) {
      const ch = css[i];
      if (quote) {
        // Inside a string: only the matching unescaped quote closes it.
        if (ch === quote && css[i - 1] !== '\\') quote = '';
      } else if (ch === '"' || ch === "'") {
        quote = ch;
      } else if (ch === '(') {
        depth++;
      } else if (ch === ')') {
        depth--;
      } else if ((ch === ';' || ch === '}') && depth === 0) {
        break;
      }
      value += ch;
    }
    const trimmed = value.replace(/\s+/g, ' ').trim();
    if (trimmed !== '') result[name] = trimmed;
    re.lastIndex = i;
  }
  return result;
}
