import type { PresetTheme } from "../types";

export const THEME_PRESETS: PresetTheme[] = [
  {
    id: "default",
    name: "Framework default",
    icon: "⚪",
    blurb: "Clear every override and let the framework defaults take over.",
    tags: ["minimal"],
    overrides: {},
  },
  {
    id: "bold",
    name: "Bold",
    icon: "🔥",
    blurb: "Saturated brand colors, larger type, snappier motion, stronger elevation.",
    tags: ["bold"],
    overrides: {
      "--sf-color-primary-source-light": "oklch(0.55 0.28 264)",
      "--sf-color-action-source-light": "oklch(0.62 0.23 18)",
      "--sf-text-scale": "1.08",
      "--sf-text-display-scale": "1.15",
      "--sf-shadow-strength": "calc(0.18 + var(--sf-is-dark) * 0.22)",
      "--sf-radius-scale": "1.1",
      "--sf-motion-scale": "0.85",
    },
  },
  {
    id: "editorial",
    name: "Editorial",
    icon: "📰",
    blurb: "Generous spacing, narrower prose, restrained shadows — long-form reading.",
    tags: ["editorial"],
    overrides: {
      "--sf-font-body": "Georgia, 'Times New Roman', serif",
      "--sf-font-heading": "Georgia, 'Times New Roman', serif",
      "--sf-text-scale": "1.05",
      "--sf-space-scale": "1.15",
      "--sf-section-scale": "1.2",
      "--sf-shadow-strength": "calc(0.04 + var(--sf-is-dark) * 0.08)",
      "--sf-radius-scale": "0.5",
    },
  },
  {
    id: "soft",
    name: "Soft Cloud",
    icon: "🫧",
    blurb: "Lower chroma, larger radii, diffuse shadows — a calmer marketing look.",
    tags: ["minimal"],
    overrides: {
      "--sf-color-primary-source-light": "oklch(0.62 0.12 250)",
      "--sf-color-secondary-source-light": "oklch(0.7 0.06 200)",
      "--sf-radius-scale": "1.6",
      "--sf-shadow-strength": "calc(0.06 + var(--sf-is-dark) * 0.1)",
      "--sf-space-scale": "1.05",
      "--sf-motion-scale": "1.1",
    },
  },
  {
    id: "high-contrast",
    name: "High Contrast",
    icon: "⚫",
    blurb: "Maximum contrast for accessibility; reduced motion respected.",
    tags: ["accessible"],
    overrides: {
      "--sf-contrast-bias": "0.15",
      "--sf-contrast-threshold": "0.5",
      "--sf-color-primary-source-light": "oklch(0.45 0.28 264)",
      "--sf-color-action-source-light": "oklch(0.4 0.25 18)",
      "--sf-shadow-strength": "calc(0.22 + var(--sf-is-dark) * 0.28)",
      "--sf-motion-scale": "0",
      "--sf-focus-ring-width": "3px",
    },
  },
  {
    id: "brutalist",
    name: "Neo-Brutalist",
    icon: "🧱",
    blurb: "Sharp corners, heavy borders, no shadows — utilitarian and uncompromising.",
    tags: ["bold"],
    overrides: {
      "--sf-radius-scale": "0",
      "--sf-shadow-strength": "0",
      "--sf-border-width-1": "2px",
      "--sf-border-width-2": "3px",
      "--sf-text-scale": "0.95",
      "--sf-motion-scale": "0.6",
    },
  },
  {
    id: "midnight",
    name: "Midnight",
    icon: "🌙",
    blurb: "Deep navy base palette with vibrant violet primary — dark-first.",
    tags: ["dark-first"],
    overrides: {
      "--sf-color-base-source-dark": "oklch(0.14 0.04 265)",
      "--sf-color-primary-source-light": "oklch(0.6 0.22 270)",
      "--sf-color-primary-source-dark": "oklch(0.72 0.2 270)",
      "--sf-color-action-source-light": "oklch(0.65 0.2 290)",
      "--sf-shadow-strength": "calc(0.05 + var(--sf-is-dark) * 0.3)",
      "--sf-radius-scale": "1.2",
    },
  },
  {
    id: "sand",
    name: "Sand & Clay",
    icon: "🏺",
    blurb: "Warm neutrals, earthy action color — organic and grounded.",
    tags: ["editorial"],
    overrides: {
      "--sf-color-primary-source-light": "oklch(0.58 0.08 60)",
      "--sf-color-action-source-light": "oklch(0.55 0.14 35)",
      "--sf-color-neutral-source-light": "oklch(0.5 0.02 70)",
      "--sf-radius-scale": "0.6",
      "--sf-shadow-strength": "calc(0.06 + var(--sf-is-dark) * 0.1)",
      "--sf-font-body": "'Georgia', serif",
    },
  },
];
