<?php
/**
 * Manual CSS admin page.
 *
 * Provides a pure-PHP admin subpage where users can paste raw CSS overrides
 * instead of using the token configurator SPA. Useful when the override CSS
 * was generated externally (e.g. via the standalone SLASHED Configurator at
 * codeslash.net/configurator) and should be applied as-is.
 *
 * When manual CSS mode is active:
 *  – The configurator SPA shows a notice and disables editing.
 *  – This page's raw CSS is injected inline after the framework stylesheet.
 *
 * @package SLASHED
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Class Slashed_Manual_CSS_Page
 */
class Slashed_Manual_CSS_Page {

	const PAGE_SLUG    = 'slashed-manual-css';
	const OPTION_KEY   = 'slashed_manual_css';
	const NONCE_KEY    = 'slashed_manual_css_save';
	const NONCE_ACTION = 'slashed_save_manual_css';

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'register_menu' ) );
		add_action( 'admin_post_slashed_save_manual_css', array( $this, 'handle_save' ) );
	}

	public function register_menu() {
		add_submenu_page(
			\Slashed_Admin::PAGE_SLUG,
			__( 'Manual CSS', 'slashed' ),
			__( 'Manual CSS', 'slashed' ),
			'manage_options',
			self::PAGE_SLUG,
			array( $this, 'render_page' )
		);
	}

	/**
	 * Handle form submission: saves manual CSS and mode toggle.
	 */
	public function handle_save() {
		if ( ! current_user_can( 'manage_options' ) ) {
			wp_die( esc_html__( 'Insufficient permissions.', 'slashed' ) );
		}

		check_admin_referer( self::NONCE_ACTION, self::NONCE_KEY );

		// All $_POST reads below are covered by the nonce check above.
		// phpcs:disable WordPress.Security.NonceVerification.Missing
		$action = isset( $_POST['slashed_action'] ) ? sanitize_key( $_POST['slashed_action'] ) : 'save';

		if ( 'clear' === $action ) {
			update_option( self::OPTION_KEY, '' );
		} else {
			// phpcs:disable WordPress.Security.ValidatedSanitizedInput.InputNotSanitized -- CSS cannot be sanitized via wp_kses without corrupting valid rules (e.g. `>`, `[attr~="val"]`). The value is validated below against injection patterns and stored raw; output is escaped at render time.
			$raw_css = isset( $_POST['slashed_manual_css'] )
				? wp_unslash( $_POST['slashed_manual_css'] )
				: '';
			// phpcs:enable WordPress.Security.ValidatedSanitizedInput.InputNotSanitized
			// CSS must not be able to break out of an inline <style> context.
			// Only block </style and <script; do NOT use wp_strip_all_tags() because
			// it removes everything between < and >, corrupting valid CSS like
			// `.parent > .child` and `[attr~="val"]`.
			if ( preg_match( '/<\/style|<script/i', $raw_css ) ) {
				wp_die( esc_html__( 'Invalid CSS: closing style or script tags are not allowed.', 'slashed' ) );
			}
			update_option( self::OPTION_KEY, $raw_css );
		}

		$manual_mode                 = ! empty( $_POST['slashed_manual_css_mode'] );
		$settings                    = Slashed_Token_Store::get_plugin_settings();
		$settings['manual_css_mode'] = $manual_mode;
		// phpcs:enable WordPress.Security.NonceVerification.Missing
		Slashed_Token_Store::update_plugin_settings( $settings );

		wp_safe_redirect(
			add_query_arg(
				array(
					'page'  => self::PAGE_SLUG,
					'saved' => '1',
				),
				admin_url( 'admin.php' )
			)
		);
		exit;
	}

	/**
	 * Get the currently stored raw CSS.
	 *
	 * @return string
	 */
	public static function get_css() {
		return (string) get_option( self::OPTION_KEY, '' );
	}

	/**
	 * Whether manual CSS mode is currently active.
	 *
	 * @return bool
	 */
	public static function is_active() {
		$settings = Slashed_Token_Store::get_plugin_settings();
		return ! empty( $settings['manual_css_mode'] );
	}

	const CONFIGURATOR_URL = 'https://slashed.codeslash.dev/configurator/';

	public function render_page() {
		if ( ! current_user_can( 'manage_options' ) ) {
			return;
		}

		$plugin_settings = Slashed_Token_Store::get_plugin_settings();
		$manual_mode     = ! empty( $plugin_settings['manual_css_mode'] );
		$saved_css       = self::get_css();
		$css_line_count  = $saved_css ? substr_count( $saved_css, "\n" ) + 1 : 0;
		$just_saved      = isset( $_GET['saved'] ) && '1' === $_GET['saved']; // phpcs:ignore WordPress.Security.NonceVerification.Recommended
		?>
		<div class="wrap">
			<h1><?php esc_html_e( 'Manual CSS', 'slashed' ); ?></h1>

			<?php if ( $just_saved ) : ?>
				<div class="notice notice-success is-dismissible">
					<p><?php esc_html_e( 'Settings saved.', 'slashed' ); ?></p>
				</div>
			<?php endif; ?>

			<p class="description" style="max-width:720px;margin-bottom:12px;">
				<?php esc_html_e( 'When Manual CSS mode is enabled, the Design Settings (token configurator) page is disabled. Paste your override CSS here instead — generated by the standalone SLASHED Configurator.', 'slashed' ); ?>
			</p>

			<p style="margin-bottom:20px;">
				<a href="<?php echo esc_url( self::CONFIGURATOR_URL ); ?>" target="_blank" rel="noopener noreferrer">
					<?php esc_html_e( '→ Open SLASHED Configurator', 'slashed' ); ?>
				</a>
				<?php esc_html_e( '— generate override CSS and paste it below.', 'slashed' ); ?>
			</p>

			<form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>">
				<input type="hidden" name="action" value="slashed_save_manual_css">
				<?php wp_nonce_field( self::NONCE_ACTION, self::NONCE_KEY ); ?>

				<!-- Mode toggle -->
				<table class="form-table" role="presentation">
					<tbody>
						<tr>
							<th scope="row"><?php esc_html_e( 'Manual CSS mode', 'slashed' ); ?></th>
							<td>
								<label>
									<input
										type="checkbox"
										name="slashed_manual_css_mode"
										value="1"
										<?php checked( $manual_mode ); ?>
									>
									<?php esc_html_e( 'Enable — use raw CSS below instead of the token configurator', 'slashed' ); ?>
								</label>
							</td>
						</tr>

						<tr>
							<th scope="row"><label for="slashed-manual-css"><?php esc_html_e( 'Override CSS', 'slashed' ); ?></label></th>
							<td>
								<?php if ( $saved_css ) : ?>
									<p class="description" style="margin-bottom:8px;">
										<?php
										printf(
											/* translators: number of lines of CSS */
											esc_html__( '%d lines of CSS currently saved.', 'slashed' ),
											(int) $css_line_count
										);
										?>
									</p>
								<?php endif; ?>
								<textarea
									id="slashed-manual-css"
									name="slashed_manual_css"
									rows="20"
									class="large-text code"
									style="font-family:monospace;font-size:13px;"
									placeholder="@layer slashed.overrides {&#10;  :root {&#10;    --sf-color-brand: oklch(60% 0.2 250);&#10;  }&#10;}"
								><?php echo esc_textarea( $saved_css ); ?></textarea>
								<p class="description">
									<?php esc_html_e( 'Paste the override CSS block from the configurator. The content is injected inline after the SLASHED framework stylesheet on every page.', 'slashed' ); ?>
								</p>
							</td>
						</tr>
					</tbody>
				</table>

				<p class="submit">
					<button type="submit" name="slashed_action" value="save" class="button button-primary">
						<?php esc_html_e( 'Save', 'slashed' ); ?>
					</button>
					<button
						type="submit"
						name="slashed_action"
						value="clear"
						class="button"
						style="margin-left:8px;"
						onclick="return confirm('<?php esc_attr_e( 'Clear all saved CSS?', 'slashed' ); ?>')"
					>
						<?php esc_html_e( 'Clear CSS', 'slashed' ); ?>
					</button>
				</p>
			</form>

		</div>
		<?php
	}
}
