<script>
  import { ui, wpSettings } from '../lib/store.svelte.js';
  import { savePluginSettings } from '../lib/wp-api.js';
  import RebemerSettings from './RebemerSettings.svelte';

  let form = $state({
    manual_css_mode: wpSettings.manual_css_mode ?? true,
    configurator_url: wpSettings.configurator_url ?? '',
  });

  let status = $state(/** @type {'idle'|'saving'|'saved'|'error'} */('idle'));
  let errorMsg = $state('');

  async function handleSubmit(e) {
    e.preventDefault();
    status = 'saving';
    errorMsg = '';
    try {
      await savePluginSettings({ ...form });
      Object.assign(wpSettings, form);
      ui.useManualCss = form.manual_css_mode;
      status = 'saved';
      setTimeout(() => { if (status === 'saved') status = 'idle'; }, 2500);
    } catch (e) {
      status = 'error';
      errorMsg = e?.message ?? 'Save failed';
    }
  }
</script>

<section class="settings-tab">
  <form class="settings-form" onsubmit={handleSubmit}>
    <h2 class="settings-tab__title">Design settings</h2>

    <!-- Token input mode -->
    <fieldset class="field-group">
      <legend class="field-group__label">Token input mode</legend>
      <p class="field-group__hint">How design token overrides are applied to this site.</p>
      <div class="radio-list">
        <label class="radio-item">
          <input type="radio" name="manual_css_mode" value={true} bind:group={form.manual_css_mode} />
          <span class="radio-item__label">Manual CSS</span>
          <span class="radio-item__hint">Paste override CSS generated by the standalone configurator</span>
        </label>
        <label class="radio-item radio-item--disabled">
          <input type="radio" name="manual_css_mode" value={false} bind:group={form.manual_css_mode} disabled />
          <span class="radio-item__label">
            Built-in configurator
            <span class="badge badge--coming">Coming in v0.8.0</span>
          </span>
          <span class="radio-item__hint">
            The visual token editor will be available when the SLASHED framework reaches v0.8.0.
          </span>
        </label>
      </div>
    </fieldset>

    <!-- Standalone configurator link -->
    <div class="field">
      <label class="field__label" for="configurator-url">Standalone configurator URL</label>
      <p class="field__hint">
        Link to the external configurator — shown in Manual CSS mode so users can open it directly.
      </p>
      <input
        id="configurator-url"
        class="field__input"
        type="url"
        placeholder="https://codeslash.net/configurator"
        bind:value={form.configurator_url}
      />
    </div>

    <!-- Other settings note -->
    <div class="settings-note">
      <p>
        CSS bundle, delivery source, builder integrations and site behaviour are configured in
        <a href={window.slashedApp?.settingsUrl ?? '#'} target="_self">Plugin Settings</a>.
      </p>
    </div>

    <!-- Actions -->
    <div class="settings-form__actions">
      <button type="submit" class="btn btn--primary" disabled={status === 'saving'}>
        {status === 'saving' ? 'Saving…' : status === 'saved' ? '✓ Saved' : 'Save settings'}
      </button>
      {#if status === 'error'}
        <span class="error-msg">{errorMsg}</span>
      {/if}
    </div>
  </form>

  <RebemerSettings />
</section>

<style>
  .settings-tab {
    padding: 1.5rem;
    max-width: 560px;
    overflow-y: auto;
    height: 100%;
    box-sizing: border-box;
  }

  .settings-tab__title {
    margin: 0 0 1.5rem;
    font-size: 1rem;
    font-weight: 600;
    color: var(--cfg-text, #111);
  }

  .settings-form {
    display: flex;
    flex-direction: column;
    gap: 1.5rem;
  }

  .field-group {
    border: none;
    margin: 0;
    padding: 0;
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
  }

  .field-group__label {
    font-size: 0.875rem;
    font-weight: 600;
    color: var(--cfg-text, #111);
  }

  .field-group__hint,
  .field__hint {
    margin: 0;
    font-size: 0.8125rem;
    color: var(--cfg-text-muted, #666);
  }

  .radio-list {
    display: flex;
    flex-direction: column;
    gap: 0.375rem;
  }

  .radio-item {
    display: grid;
    grid-template-columns: auto 1fr;
    grid-template-rows: auto auto;
    column-gap: 0.5rem;
    align-items: start;
    cursor: pointer;
    padding: 0.5rem 0.75rem;
    border-radius: 6px;
    border: 1px solid var(--cfg-border, #ddd);
    background: var(--cfg-surface, #fafafa);
  }

  .radio-item:has(input:checked) {
    border-color: var(--cfg-accent, oklch(0.6 0.18 250));
    background: color-mix(in oklch, var(--cfg-accent, oklch(0.6 0.18 250)) 6%, white);
  }

  .radio-item--disabled {
    opacity: 0.55;
    cursor: not-allowed;
  }

  .radio-item input[type="radio"] {
    grid-row: 1 / 3;
    margin-top: 0.2rem;
  }

  .radio-item__label {
    font-size: 0.875rem;
    font-weight: 500;
    color: var(--cfg-text, #111);
    display: flex;
    align-items: center;
    gap: 0.5rem;
    flex-wrap: wrap;
  }

  .radio-item__hint {
    font-size: 0.75rem;
    color: var(--cfg-text-muted, #666);
  }

  .badge {
    font-size: 0.6875rem;
    font-weight: 600;
    padding: 1px 7px;
    border-radius: 999px;
    line-height: 1.6;
    white-space: nowrap;
  }
  .badge--coming {
    background: color-mix(in oklch, oklch(0.7 0.15 55) 12%, transparent);
    color: oklch(0.5 0.15 55);
    border: 1px solid color-mix(in oklch, oklch(0.7 0.15 55) 30%, transparent);
  }

  .field {
    display: flex;
    flex-direction: column;
    gap: 0.375rem;
  }

  .field__label {
    font-size: 0.875rem;
    font-weight: 600;
    color: var(--cfg-text, #111);
  }

  .field__input {
    padding: 0.4375rem 0.625rem;
    border: 1px solid var(--cfg-border, #ddd);
    border-radius: 6px;
    background: var(--cfg-surface, #fafafa);
    color: var(--cfg-text, #111);
    font-size: 0.875rem;
    max-width: 380px;
  }

  .field__input:focus {
    outline: none;
    border-color: var(--cfg-accent, oklch(0.6 0.18 250));
    box-shadow: 0 0 0 2px color-mix(in oklch, var(--cfg-accent, oklch(0.6 0.18 250)) 20%, transparent);
  }

  .settings-note {
    padding: 0.75rem 1rem;
    border: 1px solid var(--cfg-border, #ddd);
    border-radius: 6px;
    background: var(--cfg-surface-2, #f5f5f5);
  }
  .settings-note p {
    margin: 0;
    font-size: 0.8125rem;
    color: var(--cfg-text-muted, #666);
  }
  .settings-note a {
    color: var(--cfg-accent, oklch(0.6 0.18 250));
  }

  .settings-form__actions {
    display: flex;
    align-items: center;
    gap: 0.75rem;
    flex-wrap: wrap;
  }

  .btn {
    padding: 0.5rem 1.25rem;
    border-radius: 6px;
    font-size: 0.875rem;
    font-weight: 500;
    cursor: pointer;
    border: 1px solid transparent;
    transition: background 0.15s, opacity 0.15s;
  }

  .btn:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  .btn--primary {
    background: var(--cfg-accent, oklch(0.6 0.18 250));
    color: #fff;
  }

  .btn--primary:not(:disabled):hover {
    background: color-mix(in oklch, var(--cfg-accent, oklch(0.6 0.18 250)) 85%, black);
  }

  .error-msg {
    font-size: 0.85rem;
    color: oklch(0.5 0.22 25);
  }
</style>
